In [3]:
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

In [4]:
class Neural(object) :
    def __init__(self) :
        self.inputLayerSize = 3
        self.hiddenLayerOne = 4
        self.hiddenLayerTwo = 4
        self.outputLayer = 1
        self.W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerOne)
        self.W2 = np.random.randn(self.hiddenLayerOne,self.hiddenLayerTwo)
        self.W3 = np.random.randn(self.hiddenLayerTwo,self.outputLayer)
    def sigmoid(self,z) :
        return 1.0/(1.0+ np.exp(-z))
    def dsigmoid(self,z) :
        return np.dot((self.sigmoid(z)), (1 - self.sigmoid(z)))
    def cost_function(sekf,y,yHat) :
        return np.dot((y - np.transpose(yHat)),np.transpose(y - np.transpose(yHat)))
    def forward_propagation(self,X) :
        self.z2 = np.dot(X,self.W1)
        print "Z2 : ",self.z2
        self.a2 = self.sigmoid(self.z2)
        print "A2 : ",self.a2
        self.z3 = np.dot(self.W1,self.W2)
        print "Z3 : ",self.z3
        self.a3 = self.sigmoid(self.z3)
        print "A3 : ",self.a3
        self.z4 = np.dot(self.W2,self.W3)
        print "Z4 : ",self.z4
        self.a4 = self.sigmoid(self.z4)
        print "A4 : ",self.a4
        self.yHat = np.sum(self.a4)
        print "yHat : ",self.yHat
    def backpropagation(self,Y) :
        #self.lasterror = np.dot(np.dot(self.yHat,1.0-self.yHat),Y-self.yHat)
        
        self.twoerror = np.multiply(np.multiply(self.a4,1.0-self.a4),self.W3*self.lasterror)
        print np.shape(x.twoerror)
        self.oneerror = np.multiply(np.multiply(self.a3,1.0-self.a3),self.W2*self.twoerror)
        self.zeroerror = np.multiply(np.multiply(self.a2,1.0-self.a2),self.W2*self.twoerror)
        print self.lasterror,self.twoerror,self.oneerror,self.zeroerror

In [5]:
W1 = np.random.randn(3,3)
X = np.random.randn(1,3)
print np.dot(X,W1)

[[ 0.43089835 -0.62298482  0.0652712 ]]


In [6]:
x = Neural()
x.forward_propagation(np.array([2,3,4]))
print np.shape(1.0 - x.a3)

Z2 :  [ 4.11368574 -3.6746094  -9.44161909 -5.32116473]
A2 :  [  9.83915528e-01   2.47321196e-02   7.93455306e-05   4.86329114e-03]
Z3 :  [[-1.50187379 -0.0180973   0.63078046  0.87146748]
 [ 0.1808872   0.44192362 -0.61981356 -1.06585249]
 [-2.40977524  0.55793624 -0.02121826 -0.05844145]]
A3 :  [[ 0.18214622  0.4954758   0.65266641  0.70505096]
 [ 0.5450989   0.6087173   0.34982386  0.25619263]
 [ 0.08243032  0.63597489  0.49469563  0.48539379]]
Z4 :  [[ 0.30901402]
 [ 2.51934817]
 [-0.31378197]
 [ 0.89804015]]
A4 :  [[ 0.57664458]
 [ 0.92548712]
 [ 0.42219187]
 [ 0.71054659]]
yHat :  2.63487015072
(3L, 4L)


In [53]:
x.backpropagation(1.8)
print np.shape(x.twoerror)

(4L, 1L)


ValueError: operands could not be broadcast together with shapes (3,4) (4,4) 